version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db

  db:
    image: mongo:6
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chatapp-admin
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0
volumes:
  mongo_data:
