"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"

import { useEffect, useState } from "react";
import { useStore } from "@/stores/store";
import Head from "next/head";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [mounted, setMounted] = useState(false);
  const fetchWebsiteMetadata = useStore((state) => state.fetchWebsiteMetadata);
  const websiteMetadata = useStore((state) => state.websiteMetadata);

  useEffect(() => {
    setMounted(true);
    fetchWebsiteMetadata();
  }, []);

  // Prevent hydration issues
  if (!mounted) return null;

  return (
    <html lang="en">
           <head>
        {websiteMetadata?.title && <title>{websiteMetadata.title}</title>}
        {websiteMetadata?.favicon && (
          <link rel="icon" type="image/x-icon" href={websiteMetadata.favicon} />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
